import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  authContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  authForm: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  authInput: {
    padding: "8px 12px",
    fontSize: 16,

    border: "1px solid #444",
    outline: "none",
    width: 260,
    fontFamily: "inherit",
  },
  authError: {
    color: "#f55",
    fontSize: 13,
  },
  workspace: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "100%",
  },
  statusBar: {
    display: "flex",
    alignItems: "center",
    height: 28,
    padding: "0 8px",
    fontSize: 12,
    gap: 8,
    borderTop: "1px solid",
    flexShrink: 0,
    userSelect: "none",
  },
  statusBtn: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    fontSize: 12,
    opacity: 0.7,
    padding: "2px 6px",

  },
  statusTitle: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    opacity: 0.7,
  },
  statusMetrics: {
    fontSize: 11,
    opacity: 0.5,
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    flexShrink: 0,
  },
  termContainer: {
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  disconnected: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 32,
    fontWeight: 700,
    color: "#e33",
    pointerEvents: "none",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 100,
    border: "none",
    width: "100%",
    height: "100%",
    maxWidth: "100%",
    maxHeight: "100%",
    padding: 0,
    margin: 0,
  },
  exposePanel: {
    width: "90%",
    maxWidth: 900,
    maxHeight: "80vh",

    padding: 16,
    overflow: "auto",
  },
  exposeHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  exposeCloseBtn: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    opacity: 0.5,
    fontSize: 12,
  },
  exposeCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: 12,
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  exposeSearchResults: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 8,
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  card: {
    border: "2px solid",
    overflow: "hidden",
    cursor: "pointer",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 10px",
    fontSize: 12,
    opacity: 0.8,
  },
  cardPreview: {
    margin: 0,
    overflow: "hidden",
  },
  cardCreate: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 120,
    cursor: "pointer",
  },
  exposeSearch: {
    flex: 1,
    padding: "6px 10px",
    fontSize: 14,

    border: "1px solid rgba(128,128,128,0.3)",
    outline: "none",
    fontFamily: "inherit",
  },
  exposeItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    border: "1px solid",

    cursor: "pointer",
    listStyle: "none",
  },
  exposeItemLabel: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 13,
  },
  exposeCloseItemBtn: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    opacity: 0.4,
    fontSize: 14,
    padding: "0 4px",
    fontFamily: "inherit",
  },
  exposeCreateItem: {},
  badge: {
    fontSize: 10,
    padding: "1px 5px",

    backgroundColor: "rgba(88,136,255,0.3)",
    color: "inherit",
    flexShrink: 0,
  },
  paletteBox: {

    padding: 16,
    maxHeight: "80vh",
    overflow: "auto",
    minWidth: 280,
    listStyle: "none",
  },
  paletteItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 8px",
    border: "none",

    cursor: "pointer",
    width: "100%",
    color: "inherit",
    textAlign: "left" as const,
  },
  paletteSwatches: {
    display: "flex",
    gap: 2,
  },
  swatch: {
    display: "inline-block",
    width: 14,
    height: 14,

  },
  helpBox: {

    padding: 20,
    minWidth: 300,
  },
  kbd: {
    display: "inline-block",
    padding: "2px 6px",
    fontSize: 12,

    border: "1px solid rgba(128,128,128,0.4)",
    whiteSpace: "nowrap" as const,
  },
};
