name: Deploy blit-hub

on:
  push:
    branches: [main]
    paths:
      - "js/blit-hub/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run .#deploy-blit-hub
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
